# Generated by Django 3.0.6 on 2020-06-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200516_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=models.CharField(choices=[('Electronics', (('Computer', 'Computer'), ('Laptop', 'Laptop'))), ('Furniture', (('Sofa', 'Sofa'), ('Table', 'Table'))), ('Other', 'Other')], default='Other', max_length=30),
        ),
    ]
