# Generated by Django 3.0.7 on 2020-06-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20200607_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male')], default='Not Defined', max_length=20, null=True),
        ),
    ]
