# Generated by Django 3.0.7 on 2020-06-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20200610_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='Profile1', null=True, upload_to='Profile_Pics/'),
        ),
    ]
